version: "3"

services:
  loan-simulator-api:
    container_name: loan_backend
    build:
      context: "./"
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    volumes:
      - .:/app 
      - /app/node_modules  